spring:
  cloud:
    gateway:
      routes:
        - id: msvc-users
          uri: http://msvc-users:8001
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: msvc-energy
          uri: http://msvc-energy:8002
          predicates:
            - Path=/api/energy/**
          filters:
            - StripPrefix=2

        - id: msvc-data
          uri: http://msvc-data:8003
          predicates:
            - Path=/api/data/**
          filters:
            - StripPrefix=2
