replicaCount: 1

image:
  repository: rignu/enertrack-msvc-users
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

containerPort: 8001

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres14:5432/msvc_users_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: Rig0bert0.

configMap:
  name: msvc-users-config

