apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.properties: |
    spring.application.name=msvc-auth
    server.port=8004
    
    #Habilitar actuator
    management.endpoint.health.probes.enabled=true
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always

  application.yml: |
    jwt:
      secret: {{ .Values.env.JWT_SECRET }}

    logging:
      level:
        org.springframework.web: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG

