image:
  repository: postgres
  tag: "14-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  name: postgres14

containerPort: 5432

database:
  name: msvc_users_db

credentials:
  username: postgres
  password: Rig0bert0.

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
