spring.application.name=msvc-auth
server.port=8004

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8004

#Spring cloud kubenetes

# Activa la integraci�n con Kubernetes
spring.cloud.kubernetes.enabled=true

#ConfigMap local
spring.cloud.config.enabled=false

# Service Discovery (para comunicarse entre microservicios)
spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.discovery.all-namespaces=false

# Laod balance
spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.retry.enabled=true
