apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-credentials
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  postgres-password: {{ .Values.credentials.password }}
  username: {{ .Values.credentials.username }}


